/**
 * The product's data layer.
 *
 * Every page reads through here — never a `fetch` in a component — so there is one place that
 * knows how a study is obtained and one set of types for it.
 *
 * **The deployed app never computes a study.** `apps/web` is a standalone Vercel project: the
 * engine is a Python subprocess and Vercel has no interpreter, so there is nothing to run. The
 * page therefore renders `lib/recorded-study.json`, which is produced by the real engine via
 * `scripts/record-study.mjs` and asserted against the real response schema by a test in
 * `packages/engine-model`. `source` is part of the payload so the page can say which it is
 * showing, and a reader is never left believing a recorded number was computed for them.
 *
 * See [ADR-0003](../../../docs/adr/0003-web-app-self-contained.md).
 */
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import type { StudyResult } from './study'

export interface Surface {
  readonly id: string
  readonly title: string
  readonly summary: string
  readonly status: 'shipped' | 'omitted'
  readonly reason?: string
}

export const PRODUCT = {
  name: 'LoadCurve Analyze',
  slug: 'loadcurve-analyze',
  version: '0.1.0',
  tagline:
    'Prove a grid operating plan is physically admissible — and when it is not, name the smallest contradictory constraint set and the exact relaxation each constraint needs.',
} as const

/** The surfaces that ship, and the ones deliberately left out with the reason. */
export const SURFACES: readonly Surface[] = [
  {
    id: 'cli',
    title: 'CLI',
    summary:
      'The load-bearing entry point. `loadcurve verify example` runs a full study; `loadcurve explain` prints the core and the cheapest fix.',
    status: 'shipped',
  },
  {
    id: 'engine',
    title: 'Deterministic engine',
    summary:
      'Python. Bound propagation to a fixed point, minimal unsatisfiable core extraction, exact L1 relaxation, N-1 screen. No model call anywhere in the analysis path.',
    status: 'shipped',
  },
  {
    id: 'mcp',
    title: 'MCP server',
    summary:
      'Seven tools over stdio, so any MCP client can ask whether a plan is admissible. Stateless; MCP is a transport, never a second implementation.',
    status: 'shipped',
  },
  {
    id: 'skills',
    title: 'Skills catalog',
    summary:
      'Three workflows on disk with frontmatter validation and a version gate that fails CI when a body changes without a bump.',
    status: 'shipped',
  },
  {
    id: 'studies',
    title: 'Study store',
    summary:
      'SQLite keyed by content address. A re-run of unchanged inputs is the same study, not a duplicate.',
    status: 'shipped',
  },
  {
    id: 'plugins',
    title: 'Plugin registry',
    summary:
      'Manifest-driven adapters with priority-based conflict resolution and a report of why each was accepted or rejected.',
    status: 'shipped',
  },
  {
    id: 'desktop',
    title: 'Desktop shell',
    summary:
      'Omitted. This is a study tool that runs in CI and on an operator’s terminal; an Electron wrapper would add a 150 MB download to show a window around a web app.',
    status: 'omitted',
    reason: 'No remote or GUI-only workflow exists that the CLI and web app do not already cover.',
  },
  {
    id: 'channels',
    title: 'Channel adapters',
    summary: 'Omitted. The product has no remote surface — the only consumers are the CLI, JSON and MCP.',
    status: 'omitted',
    reason:
      'Shipping a channel layer for a local-first prover would be a second path to the same capabilities.',
  },
  {
    id: 'providers',
    title: 'LLM providers',
    summary:
      'Omitted deliberately. A model call in the analysis path would make a study non-reproducible, and reproducibility is the product.',
    status: 'omitted',
    reason: 'The parts that must be exactly right are code, not generation. See ADR-0004.',
  },
]

export type StudySource = 'computed' | 'recorded'

export interface StudyPayload {
  readonly result: StudyResult
  readonly source: StudySource
  readonly note: string
}

/**
 * The study this app renders.
 *
 * Always the recorded run. There is no live path here by design: an `EngineClient` call in this
 * process would fail on Vercel (no Python) and would duplicate the contract the CLI already
 * owns. The file is regenerated by `node scripts/record-study.mjs`, which runs the real engine.
 */
export function getStudy(): StudyPayload {
  return {
    result: recordedStudy(),
    source: 'recorded',
    note: 'Recorded engine run. Run `loadcurve verify example` locally for a live result.',
  }
}

function recordedStudy(): StudyResult {
  const path = join(process.cwd(), 'lib', 'recorded-study.json')
  return JSON.parse(readFileSync(path, 'utf8')) as StudyResult
}

function packageVersion(): string {
  try {
    const raw = readFileSync(join(process.cwd(), 'package.json'), 'utf8')
    const parsed = JSON.parse(raw) as { version?: string }
    return parsed.version ?? '0.0.0'
  } catch {
    return '0.0.0'
  }
}

export function resolveVersion(): string {
  return packageVersion()
}
